# Generated by Django 2.2.10 on 2020-02-20 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acronym',
            name='acronym_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acronyms', to='database.AcronymType'),
        ),
        migrations.AlterField(
            model_name='acronym',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acronyms', to='database.Language'),
        ),
    ]
